### PR TITLE
feat(input/sql_select): espose conn sql settings

### PR DESCRIPTION
**Pull request by pcha**
⚠️ Integration tests don't working on my machine

Refs: [#1158](https://github.com/benthosdev/benthos/issues/1158)

### CODE REVIEW

**Comment by Jeffail** [comment]
Hey @pcha this should be quick to add, I'm working through some remaining v4 work but will try and make time to get to this in the week. By default I'll be merging into `main` and it'll be tagged with the new v4 release, will you need this in v3 as well?

**Comment by pcha** [comment]
He @Jeffail, than you. It depends of when the v4 will be released. I need this change incorporated for the next week, no pmather if it's in v3 or v4, do you think it would be possible?

**Comment by Jeffail** [comment]
@pcha are you willing to run a release candidate? Otherwise we'd have to back-port it for v3 and do a minor bump.

**Comment by pcha** [comment]
mmm I guess I can try with a rc for this case. If something breaks, I'll let you know and I'd ask for a minor bump in v3.

**Comment by pcha** [comment]
Hi @Jeffail We just found another workaround and it's not more a priority for us, so you can keep the regular flow and merge it whe you consider it convenient. Thank you very much for the disposition to help!

**Comment by Jeffail** [comment]
Looks good, thanks @pcha!

**Pull request merged**
