### PR TITLE
Add `cue_eval` processor

### PR DESCRIPTION
**Pull request by disintegrator**
This change introduces a new `cue_eval` processor that allows users to evaluate and transform JSON/CUE messages within the scope of a particular package in a CUE module.

In order to try this processor out:

* Checkout this branch and create a build of Benthos (e.g. with `make install`)
* Clone the benthos-cue-examples repository: https://github.com/disintegrator/benthos-cue-examples
* cd into the `cue-processor/` directory
* Start the custom Benthos build with the config.yml in that directory

The output should look something like this:

```
INFO Dropping messages.                            @service=benthos label="" path=root.output.switch.0.output
INFO Launching a benthos instance, use CTRL+C to close.  @service=benthos
INFO Listening for HTTP requests at: http://0.0.0.0:4195  @service=benthos
{"amount":0.60,"currency":"USD"}
INFO Pipeline has terminated. Shutting down the service.  @service=benthos
```

### CODE REVIEW

**Comment by gedw99** [comment]
This is really cool.

It will allow values to be streamed in, and handled with a Cue config ?

**Comment by disintegrator** [comment]
@gedw99 this is precisely the intention. You can put either JSON-encoded or CUE-encoded messages through this processor. It currently emits a result in JSON but it'll be nice to give you an option to specify that you want results in CUE.

**Comment by gedw99** [comment]
> @gedw99 this is precisely the intention. You can put either JSON-encoded or CUE-encoded messages through this processor. It currently emits a result in JSON but it'll be nice to give you an option to specify that you want results in CUE.

Thanks for letting me know. This is really useful.

WIth Cue, I am hoping to be able to use the Playground or build something in golang to help with writing up benthos configs and validating them. I was thinking about writing the GUI in golang, since cuelang is also golang.   Benthos used to have a golang / wasm gui but its abandoned. We might even be able to get a basic lsp with it

**Comment by Jeffail** [comment]
@gedw99 check out https://studio.benthos.dev, it's still in beta but its the successor to labs

**Comment by disintegrator** [comment]
@gedw99 in addition to @Jeffail's comment, I'm hoping you've also seen that we added support for generating a CUE schema for Benthos components here: https://www.benthos.dev/docs/configuration/using_cue.

**Comment by gedw99** [comment]
> @gedw99 check out https://studio.benthos.dev, it's still in beta but its the successor to labs

Wow this oils awesome !!

The layout looks pretty nice and user friendly too . 

I guess it’s not ready for CueLang based benthos yet ?

**Comment by gedw99** [comment]
> @gedw99 in addition to @Jeffail's comment, I'm hoping you've also seen that, in v4, we added support for generating a CUE schema for Benthos components here: https://www.benthos.dev/docs/configuration/using_cue.

Very cool !!

this is really going to make things way easier to work with benthos

**Comment by gedw99** [comment]
@Jeffail Your new avatar is hilarious !!!  Very apt ..

https://avatars.githubusercontent.com/u/3921142?v=4

**Comment by gedw99** [comment]
sorry to bug you but i tried out the Studio and i think do grapsp how it works to a degree.

I got as far as creating a new session, and then it wanted me to sync or upload a benthos config.
https://studio.benthos.dev/app/view/s/session-246627c7-62fd-4e42-b464-57e2c69d933d

But i kind of got stuck at this point.. Would be nice to have a walkthrough  example repo and Readme to get the newbies into the cycle of how to use it ??  

- using the Web GUI along with the CLI, and the use cases for when you use each and why ?

- Some sort of todo data transformation as a basis for the walkthrough...

**Comment by disintegrator** [comment]
I'm going to close this PR for the moment as I haven't yet had a real world use of CUE with Benthos. I'm not too keen on dumping this code on to the project without knowing how to maintain/evolve it. For anyone interested in using CUE as a process in Benthos, I can recommend taking the code from this PR and using it to build custom Benthos binary.

Check out this small repo on how to build a custom Benthos binary with input and output plugins for PostgreSQL's LISTEN/NOTIFY feature: https://github.com/disintegrator/benthos-pg-listen

**Pull request closed without merging**
