### PR TITLE
Add loop to update message visibility timeout to aws_sqs

### PR DESCRIPTION
**Pull request by miguescri**
About https://github.com/benthosdev/benthos/issues/1948

The current `aws_sqs` input doesn't update the messages' visbility timeout while they are inflight, so messages may become visible again in the queue after a while and be read again, leading to more-than-once delivery.

This MR adds a control loop in the input that keeps track of inflight messages and updates their visibility timeout regularly.

### CODE REVIEW

**Comment by miguescri** [comment]
@Jeffail hi, first time contributing and not familiar with the Benthos codebase. any advice about adding tests to this?

**Comment by miguescri** [comment]
I can't get to run the AWS SQS integration tests due to some errors related with the Localstack container.

**Comment by miguescri** [comment]
hi, @Jeffail . any suggestions on the testing side?

**Comment by Jeffail** [comment]
Hey, unfortunately using localstack as an integration testing suite is unlikely to improve over time 😅 we seem to have new issues with it every few releases. Since this is testing for very specific API interactions it might be worth considering using a mock client instead, there's an example in the output tests: https://github.com/benthosdev/benthos/blob/main/internal/impl/aws/output_sqs_test.go#L128

**Comment by miguescri** [comment]
@Jeffail i've fixed the lint error of the CI, the test error is not related to my changes

**Comment by miguescri** [comment]
hi @Jeffail . is there something else I need to do to have this merged?

**Comment by Jeffail** [comment]
Hey @miguescri, sorry this just keeps getting lost amongst everything else. I'll take another look soon, from what I remember there was a bit of refactoring I'd like to do last time I looked so I need to put some time aside to figure that out.

**Review by Jeffail — APPROVED** [review]
LGTM, thanks @miguescri!

**Comment by Jeffail** [comment]
FYI here's what I ended up doing in the tidy up: https://github.com/benthosdev/benthos/commit/e1cba9239a6b4f1579b79eb4941bf9e22620ac7e

**Pull request merged**
