### PR TITLE
bloblang: add hmac-sha jwt parsing methods

### PR DESCRIPTION
**Pull request by disintegrator**
This change adds three bloblang methods for parsing JSON Web Tokens (JWT) strings signed with HMAC-SHA. These methods are:

- `parse_jwt_hs256(signing_secret)`
- `parse_jwt_hs384(signing_secret)`
- `parse_jwt_hs512(signing_secret)`

## Notice

This change also updated github.com/golang-jwt/jwt/v4 to latest release which recently supported wrapping errors from application code correctly (i.e. jwt.ValidationError implements Unwrap since v4.2.0).

### CODE REVIEW

**Review by Jeffail — APPROVED** [review]
LGTM, thanks bae!

**Comment by Jeffail** [comment]
I mean mum

**Comment by Jeffail** [comment]
I mean @disintegrator

**Comment by disintegrator** [comment]
Cross-posting a relevant comment:
https://github.com/benthosdev/benthos/pull/1735#issuecomment-1426868096

**Pull request merged**
