### PR TITLE
added basic protobuf support to `schema_registry_decode`

### PR DESCRIPTION
**Pull request by ye11ow**
Added basic protobuf support for `schema_registry_decode`. Tested with Confluent datagen connector.

Current limitations:
* It only supports protobuf definition with only ONE message type.
* [Schema reference](https://docs.confluent.io/platform/current/schema-registry/fundamentals/serdes-develop/serdes-protobuf.html#schema-references-in-protobuf) is not supported yet.

Related to #1906

### CODE REVIEW

**Review by Jeffail — COMMENTED** [review]
Awesome @ye11ow! Any chance you'd be able to add the equivalent for `schema_registry_encode` as well?

**Comment by ye11ow** [comment]
hey @Jeffail , I haven't started to work on the encode side yet. Our own use case only requires the decode part. I don't think it is difficult to implement it though. I create a separate PR later (maybe 1 or 2 weeks later).

**Comment by Jeffail** [comment]
Hey @ye11ow, I decided to put a bit of work into adding references on top of this PR, I'm aiming to have encoding support as well. This PR will get merged at the same time which hopefully won't take long.

**Comment by Jeffail** [comment]
Okay sorted, your bits are merged via: https://github.com/benthosdev/benthos/commit/cb07600d5ccb0e1ac7399cdcb10e085d6c4aeab4

And my bits on top: https://github.com/benthosdev/benthos/commit/a3d52e2428e6c33f26cf14435ec0a585ff2f8e7e

I've added references support (both protobuf and avro) and also removed the limitation of only one message per protobuf schema. The way that encoding works with multiple message definitions is a bit hacky so I've added caveats for it on the docs page.

Thanks for kicking this off @ye11ow! We should be covering a ton of new use cases now, just missing the JSONSchema functionality but I'm quite comfortable leaving it out for now.

**Comment by ye11ow** [comment]
Hey @Jeffail, excellent work! Thank you so much for the extra work on the encoding and multiple message support! Really appreciate your time this part :-]

**Pull request closed without merging**
