### PR TITLE
Add create action to Elasticsearch output to support writing to data streams

### PR DESCRIPTION
**Pull request by bemoore34**
Added a “create” action to the Elasticsearch output, which allows writing documents to Elasticsearch Data Streams. If you attempt to write using the “index” action it will return the error:

`rejected with status [400]: only write ops with an op_type of create are allowed in data streams`

Added “create” as an action option, which calls “NewBulkCreateRequest” instead of “NewBulkIndexRequest”.

Successfully tested the update to write documents to an Elasticsearch data stream.

### CODE REVIEW

**Comment by Jeffail** [comment]
Thanks @bemoore34! Looks good, the documentation needs updating with `make docs` but I'm happy to do it on my end after merging if you want.

**Comment by bemoore34** [comment]
Thanks @Jeffail, I ran make docs and committed the change.

**Comment by bemoore34** [comment]
Sorry - it took me a while to get everything synced up and actually get the changes to the docs pushed. Looks like it is there now.

**Comment by Jeffail** [comment]
Awesome, thanks @bemoore34!

**Comment by jchoca** [comment]
Hi @Jeffail, do you happen to know when this will get released? Thanks!

**Comment by Jeffail** [comment]
Hey @jchoca I was planning one this week, I can maybe squeeze it into this evening if you're blocked.

**Comment by jchoca** [comment]
@Jeffail no, this week is great! Thanks!

**Pull request merged**
