### PR TITLE
Add nats processor that uses request reply

### PR DESCRIPTION
**Pull request by hooksie1**
This is related to #2501. It adds a processor for NATS request/reply similar to how the HTTP processor works.

tagging @codegangsta

### CODE REVIEW

**Comment by Jeffail** [comment]
Hey @hooksie1, is this implementing similar behaviour as https://github.com/benthosdev/benthos/pull/2354?

**Comment by hooksie1** [comment]
Ah yeah looks like it. I think neither me nor @codegangsta nor @mihaitodor realized that one existed. I can close in favor of that PR.

**Comment by mihaitodor** [comment]
Oops, my bad. Completely forgot there was another PR that's similar. Sorry about that!

**Comment by hooksie1** [comment]
No it's fine. I can move the testing over to that PR since it doesn't have any. Let me know what you want me to do. The other might need updated since it's a few months old

**Comment by Jeffail** [comment]
@hooksie1 yeah I've merge the original PR, it'd be good to get some tests and general improvements on top of it, are you happy to rebase and adapt your PR?

**Comment by hooksie1** [comment]
Yeah I can do that.

**Comment by hooksie1** [comment]
ok, I think I got it. I had to modify the request reply processor a tiny bit. The way it was previously, I was getting a `result store not found within batch context` error from the processor. I switched from using that convert message function to just copying the message and then returning that in the messageBatch. Let me know if that's wrong, but I couldn't get it to work the other way. Fwiw this is the config I was using:

```
input:
  http_server:
    path: /
    allowed_verbs:
      - POST
    timeout: 5s
pipeline:
  processors:
    - switch:
      - check: '@http_server_request_path == "/test"'
        processors:
          - mapping: |
              root = json()
              root.title = "test"
          - nats_request_reply:
              urls: ["nats://localhost:4222"]
              subject: "test.thing"
output:
  sync_response: {}
```

**Comment by hooksie1** [comment]
@Jeffail let me know if you need me to do anything else!

**Review by Jeffail — APPROVED** [review]
LGTM, thanks @hooksie1!

**Pull request merged**
