### PR TITLE
Add "json_path" bloblang method

### PR DESCRIPTION
**Pull request by kabukky**
This is something we are actively using.
JSONPath is very useful when handling unstructured/schemaless data.

### CODE REVIEW

**Comment by Jeffail** [comment]
Hey @kabukky this looks good but could you rework it to use the public plugin APIs? And place it within its own package similar to https://github.com/benthosdev/benthos/tree/main/internal/impl/maxmind so that we can isolate the dependencies.

Also I think it'd be a good idea to mark this as experimental in the docs like here: https://github.com/benthosdev/benthos/blob/main/internal/impl/maxmind/bloblang_geoip.go#L18 since this is going to be a really powerful feature I'd like to get user feedback before marking it stable.

**Comment by kabukky** [comment]
Hey @Jeffail, thank you so much for your comment on this.
I've reworked this PR to use the public plugin API. Is this okay? Please tell me if anything is missing.

**Comment by mihaitodor** [comment]
Small nit: Would you mind running `make deps` and committing the changes so the tests will run?

**Comment by kabukky** [comment]
Hey @mihaitodor, thanks for your comment. I've done that now, hope it helps.

**Review by Jeffail — APPROVED** [review]
Looks good, thanks @kabukky, I'll update the docs on my side.

**Pull request merged**
