### PR TITLE
kafka: reword start_from_oldest sematics

### PR DESCRIPTION
**Pull request by filippog**
Clarify that Benthos will only re-consume old messages when a new consumer group is created.

### CODE REVIEW

**Comment by Jeffail** [comment]
It also kicks in when the saved offset no longer exists

**Comment by Jeffail** [comment]
also looks like you're committing from an ooooolllllld version, sorry didn't spot that on first glance

**Comment by filippog** [comment]
> also looks like you're committing from an ooooolllllld version, sorry didn't spot that on first glance

doh! of course, sorry about the involuntary trip down memory lane

**Review by Jeffail — APPROVED** [review]

**Comment by Jeffail** [comment]
LGTM, thanks @filippog!

**Pull request merged**
