### PR TITLE
Beanstalkd

### PR DESCRIPTION
**Pull request by mkvolkov**
Added beanstalkd input/output. (Issue #718 )

### CODE REVIEW

**Comment by Jeffail** [comment]
Hey @mkvolkov, this looks great. Ideally we'd want to introduce these components using the newer public plugin APIs, there's an example here: https://github.com/benthosdev/benthos/blob/main/internal/impl/nats/input_jetstream.go, basically the way that config is defined is slightly different but other than that it's mostly the same.

**Comment by mkvolkov** [comment]
Hello @Jeffail. Thanks. You mean impl/beanstalkd/input_jetstream.go and impl/beanstalkd/output_jetstream.go, am I right?

**Comment by Jeffail** [comment]
> Hello @Jeffail. Thanks. You mean impl/beanstalkd/input_jetstream.go and impl/beanstalkd/output_jetstream.go, am I right?

Just using those as examples, I mean using the newer APIs for registering the plugins like https://pkg.go.dev/github.com/benthosdev/benthos/v4@v4.6.0/public/service#RegisterInput and so on.

**Comment by mkvolkov** [comment]
@Jeffail I've changed the configuration. It is really better.

**Comment by mihaitodor** [comment]
Nice job! I know it's a big ask, but would you consider looking at adding integration tests for it? There's https://hub.docker.com/r/websmurf/beanstalkd that's generated from https://github.com/websmurf/beanstalkd-docker/blob/main/Dockerfile, which is a trivial container. In the future, if the owner stops maintaining this container, we could run an alpine container directly and install this package on startup and then run it.

Here are some example integration tests: https://github.com/benthosdev/benthos/blob/main/internal/impl/nats/integration_jetstream_test.go or https://github.com/benthosdev/benthos/blob/main/internal/impl/nats/integration_nats_test.go. There are various `integration.StreamTests` that you can plug in there, but even the first basic ones would be great to have.

**Comment by mkvolkov** [comment]
@mihaitodor Thanks. Of course, integration tests should be added.

**Comment by mkvolkov** [comment]
Well, we have StreamTestOpenClose and SendBatch. They do not work being launched in the same suite (I think it is due to the one message topic inside the Beanstalkd), but separately tests pass.

**Comment by mkvolkov** [comment]
@mihaitodor I've added four tests.

**Comment by mihaitodor** [comment]
Cool, thank you very much! ❤️

**Review by Jeffail — APPROVED** [review]
Thanks @mkvolkov! LGTM but I'm going to make some minor adjustments after merging, one thing I'm going to change is a rename of the `tcp_address` fields to just `address`. If we want to expand support for other protocols later we can add an explicit field with `tcp` default.

**Comment by mkvolkov** [comment]
@Jeffail thank you very much! You are right about ### address field.

**Pull request merged**
