### PR TITLE
feat: use end span as parent instead of propagating input parent

### PR DESCRIPTION
**Pull request by robertmarsal**
Solves #1415 by setting the `traceparent` on http request to the value from the last span rather than propagating the input value

### CODE REVIEW

**Review by cristiprg — APPROVED** [review]

**Comment by Jeffail** [comment]
Hey @robertmarsal, looks good to me but I'm wondering whether we should make this configurable, and if so maybe instead of adding an explicit field to the HTTP components we could actually add a function to bloblang that extracts the span as a text map, that'd allow us to do something like this:

```
http:
  url: example.com
  verb: POST
  headers:
    traceparent: ${! span_text_map().traceparent }
```

And it'd be reusable elsewhere. Would that work for you? If so let me know if you're happy to do it otherwise I can take a look at adding it myself.

**Comment by robertmarsal** [comment]
Hi @Jeffail thank you for taking the time to look at this. I agree that a more generic solution would be better and solve more use cases. I am not that comfortable around that area of the code to introduce new bloblang functionality so I would appreciate your help if you have the time. Happy to help with testing/documentation :) Thanks again

**Comment by Jeffail** [comment]
Hey @robertmarsal got it implemented here: https://github.com/benthosdev/benthos/commit/177387332c27da3353ed031332dcabb5cc61edc7, any chance you can give this a try? Just want to be sure it solves your use case before closing this.

**Comment by robertmarsal** [comment]
That is awesome @Jeffail thank you so much for taking the time for this.

This works however at the moment it seems to return the main span rather than the currently active span 🤔 . If you look at my test below I was expecting the `audit_summary` span to be nested under the `http_request` rather than at the same level. The `traceparent` it receives is the one from `input_kafka` rather than `http_request`.

This is the config I am using:
```yaml
    - http_client:
        url: http://localhost:8080
        retries: 3
        headers:
          traceparent: ${! tracing_span().traceparent }
```

image

**Comment by Jeffail** [comment]
I think I know why this is, it's a general issue across a few processor implementations, will take a look this evening.

**Comment by Jeffail** [comment]
Think I got it: https://github.com/benthosdev/benthos/commit/455040b8060161432fa8baec0e40252db94ca04d, there's actually a bit more work needed to improve processor traces for proper hierarchies but I'll need to tackle that separately.

**Comment by robertmarsal** [comment]
Works as expected now thank you! 

image

I believe this and the associated issue can be closed now. Thank you again for the help with this.

**Comment by Jeffail** [comment]
Awesome, thanks for testing @robertmarsal!

**Pull request closed without merging**
