### PR TITLE
feat: Updated redis client to support usernames in URI.

### PR DESCRIPTION
**Pull request by tfendt-belong-gg**
Adds support for redis connection strings with a username in them. This allow it to work with ACL security. https://redis.io/docs/management/security/acl/

### CODE REVIEW

**Review by Jeffail — APPROVED** [review]
LGTM, thanks @tfendt-belong-gg!

**Comment by tfendt-belong-gg** [comment]
Hey @Jeffail did this make it in to the latest release?

**Comment by mihaitodor** [comment]
@tfendt-belong-gg Looks like it. See [v4.24.0](https://github.com/benthosdev/benthos/releases/tag/v4.24.0).

**Comment by tfendt-belong-gg** [comment]
Are the docs on the website supposed to update as well? I added a new example but the online docs don't show it.

**Comment by Jeffail** [comment]
The website updater got stuck, its building a new deployment right now so should be up soon.

**Pull request merged**
