### PR TITLE
Enable nacos service registry

### PR DESCRIPTION
**Pull request by intfish123**
feat: Enable to register self to nacos service registry center. In order to better collect service metrics with running in docker mode, or for more functions in futures.

### CODE REVIEW

**Comment by Jeffail** [comment]
Hey @intfish123, I'm not sure I understand what the value of this feature is. Could this potentially be something that custom builds implement rather than a feature within the main distribution of benthos?

**Comment by gedw99** [comment]
It’s this ? https://apisix.apache.org/blog/2022/02/21/nacos-api-gateway/

**Comment by intfish123** [comment]
> Hey @intfish123, I'm not sure I understand what the value of this feature is. Could this potentially be something that custom builds implement rather than a feature within the main distribution of benthos?

In more cases, we need to use service discover to collect every pod's business metrics. So that I just read these infomations from service register center, do not care about prometheus gateway. 

But now I want collect every pod's besiness metrcis, and I must to use  prometheus gateway, I feel it's inconvenient.

**Comment by intfish123** [comment]
> It’s this ? https://apisix.apache.org/blog/2022/02/21/nacos-api-gateway/

almost like this

**Pull request closed without merging**
